### ISSUE TITLE
GT深度图数据生成

### ISSUE THREAD

**Issue by yBeOne** [XYZ-qiyh/Awesome-Learning-MVS#13]
你好，我想问下MVSNet训练集的深度图怎么生成的啊？

**Comment by XYZ-qiyh** [comment]
@yBeOne 你好，MVSNet训练数据生成可参考[MVSNet论文](https://openaccess.thecvf.com/content_ECCV_2018/papers/Yao_Yao_MVSNet_Depth_Inference_ECCV_2018_paper.pdf) Sec 4.1 `Data Preparation`数据准备部分
主要包括两步：1) **泊松表面重建**和 2) **深度图渲染**
[泊松表面重建](https://github.com/mkazhdan/PoissonRecon)用于GT点云数据的表面重建，得到对应的Mesh模型；深度图渲染将Mesh渲染至各个视角下，获得对应视角下的深度图(和RGB图)。

**Comment by yBeOne** [comment]
大佬，深度图渲染有什么算法的吗。还有就是mask数据是怎么生成的呢

**Comment by yBeOne** [comment]
谢谢了，有没有MVS技术交流群可以加一下的啊

**Comment by XYZ-qiyh** [comment]
@yBeOne  [MVS/NeRF交流群](https://github.com/XYZ-qiyh/Awesome-Learning-MVS/issues/12)
