### ISSUE TITLE
colmap请教

### ISSUE THREAD

**Issue by LanZY2021** [XYZ-qiyh/Awesome-Learning-MVS#14]
嗨，您好，我是从您colmap的文章中过来的，我看了您“已知相机位姿进行colmap重建”，有一些问题，方便加您联系方式交流一下吗？我的微信是15343179786，邮箱是2246971293@qq.com，如果能得到您的指导，我将感到十分的荣幸！

**Comment by XYZ-qiyh** [comment]
@LanZY2021 你好，可以参考https://github.com/XYZ-qiyh/colmap_sparse_recon/blob/main/colmap_sparse_recon_posed.py
