### ISSUE TITLE
群二维码过期了，目前还方便入群吗

### ISSUE THREAD

**Issue by Rechal0703** [XYZ-qiyh/Awesome-Learning-MVS#4]
感谢大佬的总结，想问下还能进群吗？
要是怕回复信息有延时，也可以联系邮箱： fanmingrui17@mails.ucas.ac.cn

**Comment by XYZ-qiyh** [comment]
你好，群二维码已更新，欢迎加群一起交流学习。
（不是大佬，只是一名普通研究生）
