### ISSUE TITLE
二维码过期了

### ISSUE THREAD

**Issue by Tesla-1i** [XYZ-qiyh/Awesome-Learning-MVS#8]

**Comment by XYZ-qiyh** [comment]
你好，二维码已更新，欢迎进群交流～

**Comment by zishun** [comment]
It expired again. Could you please update it?

**Comment by XYZ-qiyh** [comment]
你好，微信群已满200人，无法通过二维码扫码进群。加我微信拉你进群 qiyh_HelloWorld
